spring:
  jpa.hibernate.ddl-auto: create
  kafka:
    consumer:
      group-id: group-foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers:  127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  datasource:
#    url: jdbc:postgresql://localhost:5432/foo_db
#    username: foo
#    password: foo
#    driverClassName: org.postgresql.Driver
spring.boot.admin.client.url: "http://localhost:8788"
management.endpoints.web.exposure.include: "*"
hbase:
  config:
    hadoop.home.dir: /foo/bin/hadoop
    hbase.zookeeper.property.clientPort: 2181
    hbase.zookeeper.quorum: fooa,foob
    hbase.master: fooa:60000
    hbase.client.pause: 500
    hbase.client.retries.number: 500
    hbase.rpc.timeout: 20000000
    hbase.client.operation.timeout: 300000
    hbase.client.scanner.timeout.period: 100000
server:
  port: 9999

kafka:
  app:
    topic:
      name: topic-foo